import type { ToolDefinition } from '@/types/tool';

export const DESIGN_TOOLS: readonly ToolDefinition[] = [
  {
    id: 26,
    slug: 'css-generator',
    name: { th: 'CSS Shadow & Gradient', en: 'CSS Shadow & Gradient' },
    description: {
      th: 'ปรับเงาและไล่สีแบบเห็นผลจริงทันที แล้วคัดลอกโค้ด CSS ไปวางใช้ได้เลย',
      en: 'Dial in shadows and gradients visually, then copy the CSS straight out.',
    },
    keywords: [
      'เงา css',
      'ไล่สี',
      'เกรเดียนต์',
      'เงากล่อง',
      'สร้าง css',
      'box shadow',
      'css',
      'gradient',
      'linear gradient',
      'generator',
    ],
    category: 'design',
    tier: 'B',
    icon: 'Paintbrush',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 27,
    slug: 'aspect-ratio',
    name: { th: 'คำนวณอัตราส่วนภาพ', en: 'Aspect Ratio Calculator' },
    description: {
      th: 'หาขนาดกว้างยาวที่คงอัตราส่วนเดิม พร้อมขนาดจริงของ Instagram, Facebook, YouTube, TikTok และ X และบอกว่าปัดเป็นจำนวนเต็มแล้วเพี้ยนเท่าไร',
      en: 'Keep a ratio while resizing, with the real pixel sizes for Instagram, Facebook, YouTube, TikTok and X, and how far whole pixels drift from the ratio.',
    },
    keywords: [
      'อัตราส่วน',
      'สัดส่วนภาพ',
      'ย่อขยายภาพ',
      'ขนาดภาพ',
      'กว้างยาว',
      'aspect ratio',
      '16:9',
      'resize',
      'dimensions',
      'proportion',
    ],
    category: 'design',
    tier: 'A',
    icon: 'Proportions',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 28,
    slug: 'color-converter',
    name: { th: 'แปลงรหัสสี', en: 'Color Converter' },
    description: {
      th: 'แปลงรหัสสีระหว่าง HEX, RGB, HSL, HSV, OKLCH และ CMYK พร้อมสร้างชุดสีอ่อนเข้มและสีคู่ตรงข้ามเป็น CSS variable',
      en: 'Convert between HEX, RGB, HSL, HSV, OKLCH and CMYK, and build tint, shade and harmony palettes as CSS variables.',
    },
    keywords: [
      'รหัสสี',
      'แปลงสี',
      'สีเฮกซ์',
      'โค้ดสี',
      'เลือกสี',
      'hex',
      'rgb',
      'hsl',
      'oklch',
      'cmyk',
      'hsv',
      'color converter',
      'color picker',
      'palette',
    ],
    category: 'design',
    tier: 'A',
    icon: 'Palette',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 29,
    slug: 'contrast-checker',
    name: { th: 'ตรวจ Contrast สำหรับธีมมืด', en: 'Contrast Checker' },
    description: {
      th: 'ตรวจคอนทราสต์ทั้งแบบ WCAG 2.x และ APCA พร้อมหาสีที่ใกล้ที่สุดที่ผ่านเกณฑ์ และตรวจชุดสีทั้งชุดพร้อมกัน',
      en: 'Check contrast by both WCAG 2.x and APCA, find the nearest colour that passes, and check a whole palette at once.',
    },
    keywords: [
      'คอนทราสต์',
      'ความต่างของสี',
      'อ่านง่าย',
      'การเข้าถึง',
      'ธีมมืด',
      'contrast',
      'wcag',
      'accessibility',
      'a11y',
      'ratio',
      'dark mode',
      'apca',
      'lc',
    ],
    category: 'design',
    tier: 'A',
    icon: 'Contrast',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 30,
    slug: 'text-cleaner',
    name: { th: 'ล้างข้อความ', en: 'Text Cleaner' },
    description: {
      th: 'ล้างช่องว่างเกิน บรรทัดว่าง อักขระล่องหน และปัญหาสระวรรณยุกต์ภาษาไทย พร้อมแปลงเลขไทยกับเลขอารบิก',
      en: 'Strip stray spaces, blank lines and invisible characters, fix loose Thai vowels and tone marks, and swap Thai and Arabic digits.',
    },
    keywords: [
      'ล้างข้อความ',
      'ลบช่องว่าง',
      'จัดข้อความ',
      'ตัวพิมพ์ใหญ่',
      'อักขระซ่อน',
      'ลบบรรทัดว่าง',
      'เลขไทย',
      'สระลอย',
      'text cleaner',
      'trim',
      'whitespace',
      'uppercase',
      'remove line breaks',
    ],
    category: 'design',
    tier: 'A',
    icon: 'Eraser',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 35,
    slug: 'image-resizer',
    name: { th: 'ย่อและบีบอัดรูป', en: 'Image Resizer & Compressor' },
    description: {
      th: 'ย่อขนาดและบีบอัดรูปในเครื่องของคุณเอง ไม่มีการอัปโหลดไฟล์ขึ้นเซิร์ฟเวอร์',
      en: 'Resize and compress images entirely in your browser — no file ever leaves your device.',
    },
    keywords: [
      'ย่อรูป',
      'บีบอัดรูป',
      'ลดขนาดไฟล์',
      'แปลงรูป',
      'ปรับขนาดภาพ',
      'image resize',
      'compress',
      'webp',
      'jpeg',
      'optimize',
      'shrink',
    ],
    category: 'design',
    tier: 'B',
    icon: 'ImageDown',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 36,
    slug: 'thai-lorem-ipsum',
    name: { th: 'ข้อความตัวอย่างภาษาไทย', en: 'Thai Lorem Ipsum' },
    description: {
      th: 'สร้างข้อความตัวอย่างภาษาไทยที่อ่านแล้วดูเป็นธรรมชาติ สำหรับงานออกแบบและจัดเลย์เอาต์',
      en: 'Generate natural-looking Thai placeholder text for design and layout work.',
    },
    keywords: [
      'ข้อความตัวอย่าง',
      'ลอเร็มไทย',
      'ข้อความจำลอง',
      'ข้อความหลอก',
      'ฟิลเลอร์',
      'placeholder',
      'lorem ipsum',
      'thai text',
      'dummy text',
      'filler',
    ],
    category: 'design',
    tier: 'A',
    icon: 'Languages',
    status: 'ready',
    needsStorage: false,
  },
];
