import type { ToolDefinition } from '@/types/tool';

export const DEVELOPER_TOOLS: readonly ToolDefinition[] = [
  {
    id: 17,
    slug: 'json-formatter',
    name: { th: 'JSON Formatter & Validator', en: 'JSON Formatter & Validator' },
    description: {
      th: 'จัดรูปแบบ ย่อขนาด เรียงคีย์ ดูเป็นต้นไม้พร้อมคัดลอกเส้นทาง แปลงเป็น TypeScript interface และชี้บรรทัดที่ผิด',
      en: 'Format, minify, sort keys, browse as a tree with copyable paths, generate a TypeScript interface, and see exactly which line failed.',
    },
    keywords: [
      'เจสัน',
      'จัดรูปแบบเจสัน',
      'ตรวจสอบ json',
      'ย่อ json',
      'json',
      'format',
      'beautify',
      'prettify',
      'minify',
      'validate',
      'parser',
      'typescript',
      'interface',
      'tree',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Braces',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 18,
    slug: 'mock-data-generator',
    name: { th: 'สร้างข้อมูลจำลอง', en: 'Mock Data Generator' },
    description: {
      th: 'สร้างข้อมูลตัวอย่างเป็น JSON หรือ CSV สำหรับทดสอบระบบ รองรับชื่อและที่อยู่แบบไทย',
      en: 'Generate sample JSON or CSV records for testing, with Thai names and addresses.',
    },
    keywords: [
      'ข้อมูลจำลอง',
      'ข้อมูลตัวอย่าง',
      'สุ่มข้อมูล',
      'ข้อมูลทดสอบ',
      'mock data',
      'fake data',
      'seed data',
      'faker',
      'csv',
      'json',
      'dummy',
    ],
    category: 'developer',
    tier: 'B',
    icon: 'Database',
    status: 'planned',
    needsStorage: false,
  },
  {
    id: 19,
    slug: 'base-converter',
    name: { th: 'แปลงเลขฐาน', en: 'Base Converter' },
    description: {
      th: 'แปลงเลขระหว่างฐาน 2 ถึง 36 รองรับเลขติดลบและเลขขนาดใหญ่เกินขีดจำกัดของ Number',
      en: 'Convert numbers between base 2 and 36, with negatives and arbitrarily large integers.',
    },
    keywords: [
      'เลขฐาน',
      'ฐานสอง',
      'ฐานสิบหก',
      'ฐานแปด',
      'ฐานสิบ',
      'ไบนารี',
      'เลขฐานสิบหก',
      'binary',
      'hex',
      'hexadecimal',
      'octal',
      'decimal',
      'base converter',
      'radix',
      'bit',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Binary',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 20,
    slug: 'regex-tester',
    name: { th: 'ทดสอบ Regex', en: 'Regex Tester' },
    description: {
      th: 'ทดสอบ regular expression กับข้อความจริง เห็นทุกจุดที่ตรงและกลุ่มที่จับได้',
      en: 'Test regular expressions against real text with highlighted matches and capture groups.',
    },
    keywords: [
      'เรกเอ็กซ์',
      'นิพจน์ปกติ',
      'ค้นหารูปแบบ',
      'จับคู่ข้อความ',
      'regex',
      'regexp',
      'regular expression',
      'pattern',
      'match',
      'capture group',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Regex',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 21,
    slug: 'cron-generator',
    name: { th: 'สร้าง Cron Expression', en: 'Cron Expression Generator' },
    description: {
      th: 'สร้างและอ่าน cron expression เป็นภาษาคน พร้อมแสดงเวลาที่จะรันครั้งถัดไป',
      en: 'Build and explain cron expressions in plain language, with upcoming run times.',
    },
    keywords: [
      'ครอน',
      'ตั้งเวลารัน',
      'งานตามเวลา',
      'ตารางเวลา',
      'crontab',
      'cron',
      'schedule',
      'expression',
      'next run',
      'job',
    ],
    category: 'developer',
    tier: 'B',
    icon: 'AlarmClock',
    status: 'planned',
    needsStorage: false,
  },
  {
    id: 22,
    slug: 'jwt-decoder',
    name: { th: 'ถอดรหัส JWT', en: 'JWT Decoder' },
    description: {
      th: 'แยก header payload และ signature ของ JWT ออกมาอ่าน พร้อมบอกว่าโทเคนหมดอายุหรือยัง',
      en: 'Split a JWT into header, payload and signature, and show whether it has expired.',
    },
    keywords: [
      'เจดับเบิลยูที',
      'ถอดรหัสโทเคน',
      'โทเคน',
      'หมดอายุ',
      'jwt',
      'token',
      'decode',
      'bearer',
      'claims',
      'payload',
      'auth',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'KeyRound',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 23,
    slug: 'url-encoder',
    name: { th: 'URL Encoder / Decoder', en: 'URL Encoder / Decoder' },
    description: {
      th: 'เข้ารหัสและถอดรหัส URL พร้อมแยกดูพารามิเตอร์ใน query string ทีละตัว',
      en: 'Encode and decode URLs and break query strings down parameter by parameter.',
    },
    keywords: [
      'เข้ารหัส url',
      'ถอดรหัส url',
      'พารามิเตอร์',
      'คิวรีสตริง',
      'ลิงก์',
      'url encode',
      'url decode',
      'percent encoding',
      'query string',
      'uri',
      'escape',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Link',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 24,
    slug: 'hash-generator',
    name: { th: 'สร้าง Hash', en: 'Hash Generator' },
    description: {
      th: 'สร้างค่าแฮช MD5, SHA-1, SHA-256, SHA-384 และ SHA-512 จากข้อความหรือไฟล์ ในเบราว์เซอร์ของคุณเอง',
      en: 'Produce MD5, SHA-1, SHA-256, SHA-384 and SHA-512 digests from text or a file, in your own browser.',
    },
    keywords: [
      'แฮช',
      'เข้ารหัสข้อความ',
      'ลายนิ้วมือข้อมูล',
      'ตรวจสอบไฟล์',
      'hash',
      'sha256',
      'sha-1',
      'sha512',
      'md5',
      'digest',
      'checksum',
      'crypto',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Hash',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 25,
    slug: 'markdown-preview',
    name: { th: 'Markdown Live Preview', en: 'Markdown Live Preview' },
    description: {
      th: 'พิมพ์ Markdown แล้วเห็นผลลัพธ์ทันทีข้างกัน บันทึกร่างไว้ในเครื่องให้อัตโนมัติ',
      en: 'Write Markdown beside a live rendered preview, with drafts auto-saved on your device.',
    },
    keywords: [
      'มาร์กดาวน์',
      'พรีวิว',
      'เขียนบันทึก',
      'แปลง markdown',
      'markdown',
      'preview',
      'md',
      'editor',
      'render',
      'readme',
    ],
    category: 'developer',
    tier: 'B',
    icon: 'FileCode',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 31,
    slug: 'base64',
    name: { th: 'Base64 Encoder / Decoder', en: 'Base64 Encoder / Decoder' },
    description: {
      th: 'เข้ารหัสและถอดรหัส Base64 รองรับข้อความภาษาไทยแบบ UTF-8 และไฟล์เป็น data URL',
      en: 'Encode and decode Base64 with full UTF-8 support, including files as data URLs.',
    },
    keywords: [
      'เบสหกสิบสี่',
      'เข้ารหัสข้อความ',
      'ถอดรหัสข้อความ',
      'แปลงข้อความ',
      'base64',
      'encode',
      'decode',
      'btoa',
      'atob',
      'data url',
      'utf-8',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'ArrowLeftRight',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 32,
    slug: 'timestamp-converter',
    name: { th: 'แปลง Unix Timestamp', en: 'Unix Timestamp Converter' },
    description: {
      th: 'แปลง Unix timestamp เป็นวันเวลาที่อ่านได้และแปลงกลับ รองรับหน่วยวินาที มิลลิวินาที และหลายไทม์โซน',
      en: 'Convert Unix timestamps to readable dates and back, in seconds or milliseconds, across time zones.',
    },
    keywords: [
      'ไทม์สแตมป์',
      'เวลายูนิกซ์',
      'แปลงเวลา',
      'อีพอค',
      'เขตเวลา',
      'timestamp',
      'unix',
      'epoch',
      'iso 8601',
      'timezone',
      'milliseconds',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Clock',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 33,
    slug: 'text-diff',
    name: { th: 'เทียบความต่างของข้อความ', en: 'Text Diff' },
    description: {
      th: 'เทียบข้อความสองชุดทีละบรรทัดหรือทีละคำ เห็นชัดว่าส่วนไหนเพิ่มเข้ามาและส่วนไหนหายไป',
      en: 'Compare two texts line by line or word by word and see exactly what was added or removed.',
    },
    keywords: [
      'เปรียบเทียบข้อความ',
      'ความต่าง',
      'ดิฟ',
      'เทียบไฟล์',
      'เทียบเวอร์ชัน',
      'text diff',
      'compare',
      'difference',
      'changes',
      'patch',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Diff',
    status: 'planned',
    needsStorage: false,
  },
  {
    id: 34,
    slug: 'uuid-generator',
    name: { th: 'สร้าง UUID / รหัสสุ่ม', en: 'UUID & Random ID Generator' },
    description: {
      th: 'สร้าง UUID v4, UUID v7 ที่เรียงตามเวลา, nanoid และรหัสสุ่มที่กำหนดชุดอักขระเองได้ ทีละมากถึงพันรายการ',
      en: 'Generate UUID v4, time-ordered UUID v7, nanoid and custom-alphabet random IDs, up to a thousand at a time.',
    },
    keywords: [
      'ยูยูไอดี',
      'รหัสสุ่ม',
      'สุ่มไอดี',
      'คีย์สุ่ม',
      'สร้างรหัส',
      'uuid',
      'guid',
      'nanoid',
      'random id',
      'v4',
      'v7',
      'token',
    ],
    category: 'developer',
    tier: 'A',
    icon: 'Fingerprint',
    status: 'ready',
    needsStorage: false,
  },
];
