import type { ToolDefinition } from '@/types/tool';

export const FINANCE_TOOLS: readonly ToolDefinition[] = [
  {
    id: 9,
    slug: 'bill-splitter',
    name: { th: 'หารบิลและหักหนี้', en: 'Bill Splitter & Debt Settler' },
    description: {
      th: 'หารค่าใช้จ่ายในกลุ่มแล้วสรุปว่าใครต้องโอนให้ใคร ด้วยจำนวนการโอนที่น้อยที่สุด',
      en: 'Split group expenses and settle who owes whom using the fewest transfers.',
    },
    keywords: [
      'หารบิล',
      'หารค่าอาหาร',
      'แชร์ค่าใช้จ่าย',
      'ใครจ่ายเท่าไร',
      'หนี้เพื่อน',
      'จ่ายคนละเท่าไร',
      'bill split',
      'split bill',
      'settle up',
      'group expense',
      'debt',
    ],
    category: 'finance',
    tier: 'C',
    icon: 'Receipt',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 10,
    slug: 'subscription-tracker',
    name: { th: 'ติดตามค่าสมาชิกรายเดือน', en: 'Subscription Tracker' },
    description: {
      th: 'รวมรายการสมัครสมาชิกทั้งหมดไว้ที่เดียว ดูยอดรวมต่อเดือนต่อปี และวันตัดรอบถัดไป',
      en: 'Keep every subscription in one list with monthly and yearly totals and next billing dates.',
    },
    keywords: [
      'ค่าสมาชิก',
      'รายเดือน',
      'ซับสคริปชัน',
      'ค่าบริการรายเดือน',
      'ตัดบัตร',
      'ค่าใช้จ่ายประจำ',
      'subscription',
      'recurring',
      'billing',
      'monthly cost',
      'netflix',
    ],
    category: 'finance',
    tier: 'C',
    icon: 'CreditCard',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 11,
    slug: 'decision-matrix',
    name: { th: 'ตารางตัดสินใจถ่วงน้ำหนัก', en: 'Weighted Decision Matrix' },
    description: {
      th: 'ให้คะแนนแต่ละตัวเลือกตามเกณฑ์ที่ถ่วงน้ำหนักไว้ แล้วดูว่าตัวเลือกไหนได้คะแนนรวมสูงสุด',
      en: 'Score each option against weighted criteria and see which one comes out ahead.',
    },
    keywords: [
      'ตัดสินใจ',
      'ถ่วงน้ำหนัก',
      'เปรียบเทียบตัวเลือก',
      'ให้คะแนน',
      'เลือกไม่ถูก',
      'ข้อดีข้อเสีย',
      'decision matrix',
      'weighted',
      'compare options',
      'pros and cons',
      'scoring',
    ],
    category: 'finance',
    tier: 'C',
    icon: 'Scale',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 13,
    slug: 'randomizer-wheel',
    name: { th: 'กงล้อสุ่ม', en: 'Randomizer Wheel' },
    description: {
      th: 'ใส่ตัวเลือกแล้วหมุนกงล้อให้ช่วยตัดสินใจ บันทึกชุดตัวเลือกไว้ใช้ซ้ำได้',
      en: 'Spin a wheel to pick from your options, with saved lists you can reuse.',
    },
    keywords: [
      'กงล้อ',
      'วงล้อ',
      'สุ่ม',
      'จับฉลาก',
      'เสี่ยงโชค',
      'กินอะไรดี',
      'random wheel',
      'spinner',
      'picker',
      'raffle',
      'lucky draw',
    ],
    category: 'finance',
    tier: 'B',
    icon: 'Disc3',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 14,
    slug: 'unit-converter',
    name: { th: 'แปลงหน่วย', en: 'Unit Converter' },
    description: {
      th: 'แปลงหน่วยความยาว น้ำหนัก อุณหภูมิ พื้นที่ ปริมาตร และความเร็ว รวมถึงหน่วยไทยอย่างไร่และวา',
      en: 'Convert length, weight, temperature, area, volume and speed, including Thai units.',
    },
    keywords: [
      'แปลงหน่วย',
      'เมตร',
      'กิโลกรัม',
      'องศา',
      'ไมล์',
      'นิ้ว',
      'ไร่',
      'ตารางวา',
      'unit converter',
      'metric',
      'imperial',
      'celsius',
      'fahrenheit',
      'kilometers',
    ],
    category: 'finance',
    tier: 'A',
    icon: 'Ruler',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 15,
    slug: 'date-calculator',
    name: { th: 'คำนวณวันเวลา', en: 'Date Calculator' },
    description: {
      th: 'หาจำนวนวันระหว่างสองวันที่ บวกลบวัน และนับวันทำการโดยหักเสาร์อาทิตย์กับวันหยุดราชการไทย พร้อมแสดง พ.ศ.',
      en: 'Find the span between two dates, add or subtract time, and count working days with weekends and Thai public holidays removed.',
    },
    keywords: [
      'คำนวณวัน',
      'ห่างกันกี่วัน',
      'บวกวัน',
      'นับวัน',
      'พ.ศ.',
      'ค.ศ.',
      'อายุ',
      'date calculator',
      'days between',
      'add days',
      'buddhist year',
      'age',
      'วันทำการ',
      'วันหยุดราชการ',
      'working days',
    ],
    category: 'finance',
    tier: 'A',
    icon: 'CalendarDays',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 16,
    slug: 'qr-generator',
    name: { th: 'สร้าง QR Code', en: 'QR Code Generator' },
    description: {
      th: 'สร้าง QR Code จากลิงก์หรือข้อความ ปรับขนาดและสีได้ แล้วดาวน์โหลดเป็นรูปทันที',
      en: 'Turn a link or text into a QR code, restyle it, and download it as an image.',
    },
    keywords: [
      'คิวอาร์โค้ด',
      'สร้างคิวอาร์',
      'สแกน',
      'พร้อมเพย์',
      'บาร์โค้ด',
      'qr code',
      'qrcode',
      'generator',
      'barcode',
      'scan',
    ],
    category: 'finance',
    tier: 'B',
    icon: 'QrCode',
    status: 'ready',
    needsStorage: false,
  },
];
