import type { ToolDefinition } from '@/types/tool';

export const PRODUCTIVITY_TOOLS: readonly ToolDefinition[] = [
  {
    id: 1,
    slug: 'pomodoro',
    name: { th: 'Focus & Pomodoro Timer', en: 'Focus & Pomodoro Timer' },
    description: {
      th: 'จับเวลาทำงานแบบโพโมโดโร สลับช่วงโฟกัสกับช่วงพัก พร้อมเก็บสถิติย้อนหลัง',
      en: 'A Pomodoro work timer that cycles focus and break intervals and keeps your session history.',
    },
    keywords: [
      'โพโมโดโร',
      'จับเวลา',
      'นาฬิกาจับเวลา',
      'โฟกัส',
      'สมาธิ',
      'ตั้งเวลาอ่านหนังสือ',
      'pomodoro',
      'timer',
      'focus',
      'productivity',
      'study timer',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'Timer',
    status: 'ready',
    needsStorage: true,
    hasItemCounter: true,
  },
  {
    id: 2,
    slug: 'eisenhower-matrix',
    name: { th: 'Eisenhower Matrix', en: 'Eisenhower Matrix' },
    description: {
      th: 'จัดลำดับงานด้วยตารางสี่ช่อง ด่วน/สำคัญ เพื่อตัดสินใจว่าต้องลงมือทำอะไรก่อน',
      en: 'Sort tasks into the urgent/important four-quadrant grid to decide what to do first.',
    },
    keywords: [
      'ไอเซนฮาวร์',
      'จัดลำดับความสำคัญ',
      'เร่งด่วน',
      'สำคัญ',
      'ตารางงาน',
      'บริหารเวลา',
      'eisenhower',
      'matrix',
      'priority',
      'urgent',
      'important',
      'todo',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'Grid2x2',
    status: 'ready',
    needsStorage: true,
    hasItemCounter: true,
  },
  {
    id: 3,
    slug: 'flashcards',
    name: { th: 'Quick Flashcards', en: 'Quick Flashcards' },
    description: {
      th: 'สร้างบัตรคำแบบพลิกอ่าน ทบทวนได้ทันทีโดยไม่ต้องสมัครสมาชิก',
      en: 'Build flip cards and start reviewing right away — no account required.',
    },
    keywords: [
      'บัตรคำ',
      'แฟลชการ์ด',
      'ท่องศัพท์',
      'ทบทวน',
      'ความจำ',
      'ท่องจำ',
      'flashcard',
      'cards',
      'memorize',
      'review',
      'vocabulary',
      'quiz',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'Layers',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 4,
    slug: 'target-grade',
    name: { th: 'คำนวณคะแนนที่ต้องได้', en: 'Target Grade Calculator' },
    description: {
      th: 'คำนวณว่าต้องทำคะแนนสอบที่เหลืออีกเท่าไรถึงจะได้เกรดตามเป้าที่ตั้งไว้',
      en: 'Work out the score you still need on remaining exams to reach your target grade.',
    },
    keywords: [
      'คะแนนที่ต้องได้',
      'เกรดเป้าหมาย',
      'คำนวณคะแนน',
      'สอบปลายภาค',
      'สอบกลางภาค',
      'ต้องได้กี่คะแนน',
      'target grade',
      'required score',
      'exam',
      'final grade',
      'calculator',
    ],
    category: 'productivity',
    tier: 'A',
    icon: 'Target',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 5,
    slug: 'habit-tracker',
    name: { th: 'Habit Tracker', en: 'Habit Tracker' },
    description: {
      th: 'ติดตามนิสัยรายวันและดูสถิติความต่อเนื่องบนปฏิทินแบบเห็นภาพรวมทั้งเดือน',
      en: 'Track daily habits and watch your streaks build across a month-at-a-glance calendar.',
    },
    keywords: [
      'นิสัย',
      'ติดตามนิสัย',
      'ทำต่อเนื่อง',
      'สตรีค',
      'วินัย',
      'เช็กลิสต์รายวัน',
      'habit',
      'tracker',
      'streak',
      'daily',
      'routine',
      'consistency',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'CalendarCheck',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 6,
    slug: 'spaced-repetition',
    name: { th: 'Spaced Repetition Planner', en: 'Spaced Repetition Planner' },
    description: {
      th: 'วางแผนวันทบทวนตามหลักการทิ้งช่วง ช่วยให้จำได้นานขึ้นโดยใช้เวลาอ่านน้อยลง',
      en: 'Schedule review dates using spaced repetition so material sticks with less study time.',
    },
    keywords: [
      'ทบทวนแบบทิ้งช่วง',
      'ตารางทบทวน',
      'ความจำระยะยาว',
      'อ่านหนังสือ',
      'แผนอ่านหนังสือ',
      'spaced repetition',
      'review schedule',
      'anki',
      'sm-2',
      'memory',
      'study plan',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'Repeat',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 7,
    slug: 'gpa-calculator',
    name: { th: 'คำนวณเกรดเฉลี่ย', en: 'GPA Calculator' },
    description: {
      th: 'คำนวณ GPA รายเทอมและ GPAX สะสม จากหน่วยกิตและเกรดของแต่ละวิชา',
      en: 'Compute per-term GPA and cumulative GPAX from course credits and grades.',
    },
    keywords: [
      'เกรดเฉลี่ย',
      'จีพีเอ',
      'คำนวณเกรด',
      'หน่วยกิต',
      'เกรดสะสม',
      'จีแพ็ก',
      'gpa',
      'gpax',
      'grade point average',
      'credits',
      'transcript',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'GraduationCap',
    status: 'planned',
    needsStorage: true,
  },
  {
    id: 8,
    slug: 'word-counter',
    name: { th: 'นับคำและเวลาอ่าน', en: 'Word & Reading Time Counter' },
    description: {
      th: 'นับคำ ตัวอักษร ประโยค และย่อหน้า ตัดคำไทยจริงด้วย Intl.Segmenter พร้อมเวลาอ่าน เวลาพูด และคำที่พบบ่อย',
      en: 'Count words, characters, sentences and paragraphs with real Thai word segmentation, plus reading time, speaking time and word frequency.',
    },
    keywords: [
      'นับคำ',
      'นับตัวอักษร',
      'เวลาอ่าน',
      'จำนวนคำ',
      'นับย่อหน้า',
      'ความยาวบทความ',
      'word count',
      'character count',
      'reading time',
      'letters',
      'paragraphs',
    ],
    category: 'productivity',
    tier: 'A',
    icon: 'FileText',
    status: 'ready',
    needsStorage: false,
  },
  {
    id: 12,
    slug: 'countdown',
    name: { th: 'นับถอยหลังวันสำคัญ', en: 'Event Countdown' },
    description: {
      th: 'นับถอยหลังถึงวันสอบ วันเดินทาง หรือเดดไลน์ เห็นเวลาที่เหลือแบบเรียลไทม์',
      en: 'Count down to exams, trips or deadlines with a live remaining-time display.',
    },
    keywords: [
      'นับถอยหลัง',
      'วันสำคัญ',
      'เดดไลน์',
      'เหลืออีกกี่วัน',
      'วันสอบ',
      'วันครบกำหนด',
      'countdown',
      'days left',
      'deadline',
      'event timer',
      'due date',
    ],
    category: 'productivity',
    tier: 'C',
    icon: 'CalendarClock',
    status: 'planned',
    needsStorage: true,
  },
];
